FROM ubuntu

RUN apt-get update && apt-get install -y git

WORKDIR /app

RUN git clone


FROM maven:3.9.8-amazoncorretto-17 AS build

WORKDIR /app

COPY pom.xml .
COPY src ./src

RUN mvn clean package


FROM tomcat

RUN rm -rf /usr/local/tomcat/webapps/*

COPY --from=build /app/target/Gerenciamento_de_Abrigos.war /usr/local/tomcat/webapps/ROOT.war

EXPOSE 8080

CMD ["catalina.sh", "run"]